# -*- coding: utf-8 -*-
"""GuessingGameProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1JWj-6vj968lgnjekwJTOSalpbta5VQ
"""

"""
Created on Fri Dec 13 22:59:47 2024

@author: josephersalto
"""

import random

def num_guessing_game():
    secret_number = random.randint(1, 10)
    attempts = 0
    with open('final_project.txt' , 'w') as file:
        message = 'Im thinking of a number between 1 and 10.'
        print(message)
        file.write(message + '\n')


        while True:
            guess = int(input("Take a guess: "))
            attempts += 1
            file.write(f"Guess {attempts}: {guess}\n")

            if guess < secret_number:
                print("Number too low!")
                file.write("Number too low!\n")
            elif guess > secret_number:
                print("Number too high!")
                file.write("Number too high!\n")
            elif guess == secret_number:
                print(f"Congratulations! You guessed the number in {attempts} attempts.")
                file.write(f"Congratulations! You guessed the number in {attempts} attempts.\n")
                break
            else:
                print("Invalid input. Please enter a number.")
                file.write("Invalid input. Please enter a number.\n")


num_guessing_game()